name: 'Automatic build'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: false

      - name: Check ruby & gem versions (디버깅용)
        run: |
          ruby -v
          gem -v
          bundle -v || true

      - name: Update RubyGems & Install Bundler (update)
        run: |
          gem update --system
          gem install bundler -v '2.4.13' || gem install bundler
          bundle -v
          gem -v
      - name: Install gems (bundle install) 
        run: |
          bundle config set --local path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Deploy
        run: bash tools/deploy.sh


